name: Mac-Per-Papa
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Installa Ngrok
        run: brew install --cask ngrok
      - name: Avvia Tunnel
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 5900 &
      - name: Attiva VNC
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvncpw -vncpw ${{ secrets.VNC_PASSWORD }} -restart -agent -privs -all
      - name: Aspetta Connessione
        run: sleep 21600
